# Jekyll config

# Site settings
title: Co-op accessibility exercise
description: Return a leaky flour bag is a made-up Co-op journey, filled with accessibility issues. Your task is to find them all!t
baseurl: ""
url: "https://return-leaky-flour.herokuapp.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
